### PR TITLE
Bugs fix on layers

### PR DESCRIPTION
**Pull request by syk1k**
@adelekeoadelaja @Kaoschuks please review
@phil196000

### CODE REVIEW

**Review by adelekeoadelaja — APPROVED** [review]
@phil196000 good to go

**Review by adelekeoadelaja — APPROVED** [review]
@phil196000 good to merge

**Review by adelekeoadelaja — APPROVED** [review]
@phil196000 good to go

**Review by phil196000 — APPROVED** [review]
Ok to merge

**Pull request merged**
